LidarTopPreprocess.so: LidarTopPreprocess.c
	g++ -Wall -O3 -shared LidarTopPreprocess.c -o LidarTopPreprocess.so -fPIC
LidarTopAndFrontPreprocess.so: LidarTopAndFrontPreprocess.c
	g++ -Wall -O3 -shared LidarTopAndFrontPreprocess.c -o LidarTopAndFrontPreprocess.so -fPIC
