LidarPreprocess.so: LidarPreprocess.c
	g++ -Wall -O3 -shared LidarPreprocess.c -o LidarPreprocess.so -fPIC
LidarTopPreprocess.so: LidarTopPreprocess.c
	g++ -Wall -O3 -shared LidarTopPreprocess.c -o LidarTopPreprocess.so -fPIC